os: linux
dist: xenial
sudo: required
language: node_js
node_js: 8.11.3

branches:
  only:
  - master


cache:
  directories:
    - node_modules
    
before_install:
  - chmod +x ./deploy.sh

script:
    - ./deploy.sh

branch: master