title: 企業管理碩士班筆記
description: 臺北大學 商學院碩士班 107
base: /note/
themeConfig:
  sidebar:
    - title: '管理學'
      children:
        - ['/src/管理學/ch1','第一章 管理與組織概論']
        - ['/src/管理學/ch2','第二章 組織文化與環境的限制']
        - ['/src/管理學/ch3','第三章 綜合性的管理議題']
    - title: '經濟學'
      children:
        - ['/src/經濟學/經濟學','總體經濟']
    - title: '會計學'
      children:
        - ['/src/會計/ch08','第八章 現金及內部控制']
        - ['/src/會計/ch09','第九章 應收款項']
        - ['/src/會計/ch10','第十章 不動產廠房設備']
        - ['/src/會計/ch11','第十一章 無形資產、投資性不動產、生物資產與農產品']
        - ['/src/會計/ch12','第十二章 流動負債與負債準備']
        - ['/src/會計/ch13','第十三章 非流動負債']
        - ['/src/會計/ch15','第十五章 股本、資本公積與庫藏股票']
        - ['/src/會計/ch16','第十六章 權益、保留盈餘與股利']
        - ['/src/會計/ch17','第十七章 現金流量表']
    - title: '行銷管理'
      children:
        - ['/src/行銷管理/CH1','第一章 行銷導論']
        - ['/src/行銷管理/CH2','第二章 公司與行銷策略']
        - ['/src/行銷管理/CH5','第五章 公司與行銷策略']
        - ['/src/行銷管理/CH6','第六章 顧客導向行銷策略']
        - ['/src/行銷管理/CH7','第七章 產品、服務與品牌']
        - ['/src/行銷管理/CH9','第九章 了解與掌握顧客價值']
    - title: '統計 & SPSS'
      children:
        - ['/src/SPSS/SPSS','統計&SPSS']
  repo: "graysonastral/note"
  repoLabel: "GitHub"
  editLinks: true
  editLinkText: 編輯這個頁面
